spring:
  profiles:
    #    active: prod
    active: mysql
  #    active: oracle
  #    active: tielu
  #    active: hou
  thymeleaf:
    cache: false
  rabbitmq:
    addresses: 10.94.21.117
    host: 15672
    username: DevlinKim
    password: Test.1234
    listener:
      direct:
        prefetch: 5
      simple:
        max-concurrency: 20
        concurrency: 10

mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
    auto-mapping-behavior: full
    log-impl: org.apache.ibatis.logging.stdout.StdOutImpl
  mapper-locations: classpath:/MapperXml/*


