spring:
  datasource:
    driver-class-name: com.mysql.jdbc.Driver
    username: root
    password: Alpha.1111
    url: jdbc:mysql://103.45.172.175:3306/BlogDB?nullCatalogMeansCurrent=true&useUnicode=true&characterEncoding=utf-8&useSSL=false&serverTimezone=GMT%2B8
    dbcp2:
      max-idle: 10
      max-wait-millis: 10000